#!/usr/bin/env zsh

source "${0:a:h}/step-renewer.zsh"
source "${0:a:h}/config.zsh"

function {
    typeset config_map_name
    if [[ ${1:-} = '--config' ]]; then
        config
    else
        if [[ $STEP_RENEWER_UNSAFE_LOGGING = 1 ]]; then
            cat "$BINDING_CONTEXT_PATH"
            print
        fi
        process_binding_context "$BINDING_CONTEXT_PATH"
    fi
} "$@"
